name = "AJD"
uuid = "a46c7bb5-82a2-4996-a5f0-af050a3cd1ba"
authors = ["Mustafa Erdenay Gürol erdenay16@gmail.com"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"


